apiVersion: v1
kind: Service
metadata:
  name: zookeeper-headless
  namespace: default # {"$kpt-set":"namespace"}
  labels:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/name: zookeeper
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/component: zookeeper
    app.kubernetes.io/name: zookeeper
  ports:
  - name: tcp-client
    port: 2181
    targetPort: client
  - name: follower
    port: 2888
    targetPort: follower
  - name: tcp-election
    port: 3888
    targetPort: election
  clusterIP: None
  publishNotReadyAddresses: true
